### ISSUE TITLE
Multiple-line command may cause failed

### ISSUE THREAD

**Issue by NichtsHsu** [GuillaumeFalourd/test-cli-commands-action#10]
For example:

```yaml
- uses: GuillaumeFalourd/assert-command-line-output@v2.2
  with:
    command_line: |
        a_very_long_command --that --need \
        --multiple --lines --to --write
    assert_file_path: path/to/assert.txt
```

Github action will execute:

```bash
a_very_long_command --that --need \
    --multiple --lines --to --write
&> output.txt || true # <- a new line here
```

One method that works is to use single quoted string:

```yaml
    command_line: 'a_very_long_command --that --need
        --multiple --lines --to --write'
```
