### ISSUE TITLE
line 3: [: !=: unary operator expected

### ISSUE THREAD

**Issue by JonathanAtCenterEdge** [GuillaumeFalourd/test-cli-commands-action#9]
Using `contains` on any inputs like so

```yaml
    - name: Container should contain new image version
      uses: GuillaumeFalourd/assert-command-line-output@v2.1
      with:
        command_line: ls
        contains: deployment.yaml
        expected_result: PASSED
```

results in
![chrome_0SYhAfRREA](https://github.com/GuillaumeFalourd/assert-command-line-output/assets/91483632/143bea92-5668-462a-8e3e-3d1a9bdf54af)

**Comment by GuillaumeFalourd** [comment]
Hi @JonathanAtCenterEdge , how are you doing? 😄 

Thank you for opening this issue!

I observed a bug setting the output value in the script, could you please try again using the `@v2.2` action version?

```yaml
    - name: Container should contain new image version
      uses: GuillaumeFalourd/assert-command-line-output@v2.2
      with:
        command_line: ls
        contains: deployment.yaml
        expected_result: PASSED
 ```
